language: python
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
- pip install coveralls
install:
- pip install -r requirements.txt
- python setup.py install
script:
- export TRUNDLER_KEY=$TRUNDLER_KEY
- coverage run --source trundlerPy -m py.test
- coverage report
after_success:
- coveralls
- codecov