language: python
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
- pip install coveralls
install:
- pip install -r requirements.txt
- python setup.py install
script:
- export TRUNDLER_KEY=$TRUNDLER_KEY
- coverage run --source trundlerpy -m py.test
- coverage report
after_success:
- coveralls
- codecov
env:
  global:
    secure: gjS+Rki8ridtC2A340tTZlofMqAcbelP3sez/6kAXuV8/GoZpoPPgHEmx5/mHjU9rngNQBY/mlaoAJGHTIg027rB26071ahnCbqs9aLNCId96omgsBuz3+7EczEHq96jrMfI4Ym8Iy070EF5KwIEKT2dkMGG1ApWbGcuJQA12Mf6bR1aSrmnGeR4i6DR51F6aGmOvKB5JOii4K1nnpChE5ufkXzIvRxf+IEfSwtr57Efsd7d/uMMSoPa5ZAAPAR0Z58W7Cgj5L0fmP/zaEGva3QAlnyAcXgvflNMx0JK2uoFMsmZGw/ozvkjAXgiV4B1CNjNngV5JNkzMBnSNUyLuTUwrOIiwGEXNLX3UGxjjtZSGRAXjolZmvR+P3lkE2h3jlHLiyIXCA3Salrmez5mmcQGzYzcn7Kk4433M5rn/cY57HI6mYk+5dcoV5hkfOTfWeX0jnT5p5yFhWTzB8YUy/HeTtHJMATmP9S0K5IGMQIxXr0MOiVCa4vXrPxVirtLANBh6WjGZKM62qqbznaHdI9lSBMVOURYDVe66ewRtGVCKIJ4kQ6IH4XETlL4tpCprNz9pp9f5WJhnM/c1MYN8VZnmWtsPr+DRAQ5k6CN0r/pOJ3Yfo8LEvZfCQRnPmKO7JC97CS7fQtCVwJPS8jdEyv3FWJuJ8jb1fTzaEZ0dxo=
